@startuml
title Shape Factory
abstract class Shape {
    + public Draw() 
}
class Circle {
    + public Draw()
}
class Square {
    + public Draw()
}
class Rectangle {
    + public Draw()
}
class Factory {
    + public Create(string) :Shap
}
Circle <|.up. Shape
Square <|.up. Shape
Rectangle <|.up. Shape

Rectangle <.down. Factory:Create(string) :Shap
Circle <.down. Factory:Create(string) :Shap
Square <.down. Factory:Create(string) :Shap
@enduml